/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i dbustypes.h -p e-gdbus-emailsession-proxy /home/meego/git/evolution-data-server/mail/daemon/e-mail-data-session.xml org.gnome.evolution.dataserver.mail.Session
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "e-gdbus-emailsession-proxy.h"

/*
 * Implementation of interface class OrgGnomeEvolutionDataserverMailSessionInterface
 */

OrgGnomeEvolutionDataserverMailSessionInterface::OrgGnomeEvolutionDataserverMailSessionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgGnomeEvolutionDataserverMailSessionInterface::~OrgGnomeEvolutionDataserverMailSessionInterface()
{
}

OrgGnomeEvolutionDataserverMailSessionInterface * OrgGnomeEvolutionDataserverMailSessionInterface::instance (QObject *parent)
{
  static OrgGnomeEvolutionDataserverMailSessionInterface *priv_obj = NULL;
  
  if (!priv_obj) {
      priv_obj = new OrgGnomeEvolutionDataserverMailSessionInterface (QString ("org.gnome.evolution.dataserver.Mail"),
								QString ("/org/gnome/evolution/dataserver/Mail/Session"),
								QDBusConnection::sessionBus(), parent);
  }
  
  return priv_obj;
}
