/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i dbustypes.h -p e-gdbus-emailfolder-proxy /home/meego/git/evolution-data-server/mail/daemon/e-mail-data-folder.xml org.gnome.evolution.dataserver.mail.Folder
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "e-gdbus-emailfolder-proxy.h"

/*
 * Implementation of interface class OrgGnomeEvolutionDataserverMailFolderInterface
 */

OrgGnomeEvolutionDataserverMailFolderInterface::OrgGnomeEvolutionDataserverMailFolderInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgGnomeEvolutionDataserverMailFolderInterface::~OrgGnomeEvolutionDataserverMailFolderInterface()
{
}

